version: '3.1'

services:
  db:
    image: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: coursedb
      MYSQL_ROOT_PASSWORD: springCRUD

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - db

  spring-service:
    build: ./SpringCRUD
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure
    
  angular-service:
    build: ./AngularCRUD
    ports:
      - "4200:80"
    expose:
      - "4200"
    restart: unless-stopped