name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14', '16' ]
    name: Node ${{ matrix.node }} sample
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
          
      - name: Unit Tests
        run: ./SpringCRUD/gradlew -p ./SpringCRUD test
        
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.31
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Unit Test Results
          files: SpringCRUD/build/test-results/test/TEST*.xml
          report_individual_runs: true
          deduplicate_classes_by_file_name: false
        
      - name: Unit Tests and static code analysis
        if: success()
        run: ./SpringCRUD/gradlew -p ./SpringCRUD check
        
      - name: Build with Gradle
        run: ./SpringCRUD/gradlew -p ./SpringCRUD build
        
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: npm install --prefix ./AngularCRUD/
      - run: npm run build --prefix ./AngularCRUD/
